In [16]:
##4.판다스 data 그룹
import pandas as pd
from pandas import DataFrame
df_data=pd.read_csv('경찰청 강원도경찰청_음주교통사고 발생 현황_20201231.csv',encoding="euc-kr")
df=DataFrame(df_data)
df

     연도   발생  사망    부상
0  2020  620  11  1053
1  2019  493  18   797
2  2018  680  14  1165
3  2017  780  18  1338
4  2016  708  18  1266

In [12]:
df_1=DataFrame(df_data,columns=['연도','발생'])
df_1

     연도   발생
0  2020  620
1  2019  493
2  2018  680
3  2017  780
4  2016  708

In [13]:
df_2=DataFrame(df_data,columns=['사망','부상'])
df_2

   사망    부상
0  11  1053
1  18   797
2  14  1165
3  18  1338
4  18  1266

In [17]:
df.iloc[:2,:2]

     연도   발생
0  2020  620
1  2019  493